### ISSUE TITLE
[10.0] Impossible to manually set geo_point values

### ISSUE THREAD

**Issue by soluxSG** [OCA/geospatial#140]
I need to set latitude and longitude manually in Odoo 10 but it will not allow me. I already tried with compute = 'method' in the geo_point and I get an error when I use the from_latlon method. Please help me.

**Comment by yvaucher** [comment]
There are multiple method to do that. 

The one I explained on mailing list https://odoo-community.org/groups/geospatial-48

``` python
from shapely.geometry import Point

my_point = Point(731452, 5875278).wkt

# assuming we want to set a point on a partner
self.env['res.partner'].create({'name': 'Foo', 'point': my_point})
```

You can also directly edit a geo_field if you give it a text widget putting a string like the wkt format: "POINT(731452, 5875278)" but in that can you loose the visibility of the map widget.


Or maybe you just want to use the dedicated widget `FieldGeoPointXY`

``` xml
<field name="geo_point" widget="geo_point_xy"/>
```

Otherwise it could be an issue with assignation.
Can you provide a part of your code and the errors you get if any?

**Comment by soluxSG** [comment]
I have this:

```
    @api.model
    @api.depends('terreno_coordenada_x', 'terreno_coordenada_y')
    def get_geo_point(self):
    	if self.terreno_coordenada_x and self.terreno_coordenada_y:
    		self.terreno_coordenada_map = Point(731452.399608894,5875278.22228421).wkt
    	else:
    	        return False
```
    
    terreno_coordenada_map = geo_fields.GeoPoint(
        string='Coordenada',
        store=True,
        compute='get_geo_point'
    )

I get the next error:

```
Traceback (most recent call last):
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/SIGTE/SIGTE-dev/SIGTE/addons/web/controllers/main.py", line 878, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/models.py", line 5474, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/models.py", line 5372, in _onchange_eval
    method_res = method(self)
  File "/home/SIGTE/SIGTE-dev/modulos/grupotecho_fmv_mapa/models/fmv_postulante.py", line 75, in onchange_geo_point
    x, y = geojson.loads(self.terreno_coordenada_map).coordinates
  File "/home/SIGTE/SIGTE-dev/SIGTE/local/lib/python2.7/site-packages/geojson/codec.py", line 55, in loads
    **kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/local/lib/python2.7/site-packages/simplejson/__init__.py", line 533, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/home/SIGTE/SIGTE-dev/SIGTE/local/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/home/SIGTE/SIGTE-dev/SIGTE/local/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by yvaucher** [comment]
Okay seems assignation doesn't work. We didn't implement it as we did for the write.

Thus you can only provide a geojson value.

```
        value can be geojson, wkt, shapely geomerty object.
        If geo_direct_write in context you can pass diretly WKT
```

Please try:
``` python
@api.model
@api.depends('terreno_coordenada_x', 'terreno_coordenada_y')
def get_geo_point(self):
    if self.terreno_coordenada_x and self.terreno_coordenada_y:
         self.terreno_coordenada_map = (
             '{"type": "Point", "coordinates": [731452.399608894, 5875278.22228421]}'
         )
    else:
        return False
```

**Comment by soluxSG** [comment]
I tried it once: setting directly a geojson value in the geo_point field and i get the next error:

```
Traceback (most recent call last):
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/SIGTE/SIGTE-dev/SIGTE/addons/web/controllers/main.py", line 878, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/models.py", line 5499, in onchange
    for name in dirty
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/models.py", line 5499, in <dictcomp>
    for name in dirty
  File "/home/SIGTE/SIGTE-dev/SIGTE/SIGTE/fields.py", line 818, in convert_to_onchange
    return self.convert_to_read(value, record)
  File "/home/SIGTE/SIGTE-dev/modulos/base_geoengine/fields.py", line 61, in convert_to_read
    shape = self.load_geo(value)
  File "/home/SIGTE/SIGTE-dev/modulos/base_geoengine/fields.py", line 78, in load_geo
    return wkbloads(wkb, hex=True) if wkb else False
  File "/home/SIGTE/SIGTE-dev/SIGTE/local/lib/python2.7/site-packages/shapely/wkb.py", line 14, in loads
    return reader.read_hex(data)
  File "/home/SIGTE/SIGTE-dev/SIGTE/local/lib/python2.7/site-packages/shapely/geos.py", line 416, in read_hex
    raise ReadingError("Could not create geometry because of errors "
ReadingError: Could not create geometry because of errors while reading input.

```
