### ISSUE TITLE
[10.0][11.0][12.0] Odoo Server Error - init_postgis - (issue when using postgres 12)

### ISSUE THREAD

**Issue by javierlaris** [OCA/geospatial#142]
When i'm installing Geospatial support for Odoo (v10.0) i get this error:

```
Traceback (most recent call last):
  File "/home/admin01/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/admin01/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/admin01/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/admin01/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/admin01/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/admin01/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/admin01/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/admin01/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/admin01/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/admin01/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/admin01/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/admin01/odoo/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/admin01/odoo/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/admin01/odoo/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/admin01/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/home/admin01/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/admin01/odoo/odoo/modules/loading.py", line 129, in load_module_graph
    getattr(py_module, pre_init)(cr)
AttributeError: 'module' object has no attribute 'init_postgis'
```

i need help

**Comment by megantaradika** [comment]
up

**Comment by yvaucher** [comment]
Duplicate with https://github.com/OCA/geospatial/issues/137

**Comment by yvaucher** [comment]
This error seems to come from the 'pre_init_hook'
https://github.com/OCA/geospatial/blob/10.0/base_geoengine/__manifest__.py#L31

Which is defined here:

https://github.com/OCA/geospatial/blob/10.0/base_geoengine/geo_db.py#L12

As a work around, you can try to comment the line in the manifest and do the following command by hand:

```
SELECT
            tablename
        FROM
            pg_tables
        WHERE
            tablename='spatial_ref_sys';
```

If you get something do nothing.

Otherwise do:

```
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
```

**Comment by yvaucher** [comment]
@javierlaris  and @megantaradika What is your version of Odoo and what is your version of python?

Locally I tested the install and it works without error on Odoo 10.0 and python 2.7.9.

**Comment by sarahosay** [comment]
hello, i have python 2.7.12 and Odoo 10 installed in my computer. I also had the same error while installing geoengine. I already tried doing the above suggestions but I still get an error:

ParseError: "Error while validating constraint

Field `gist_index` does not exist

Error context:
View `ir.model.fields.form.geo`
[view_id: 206, xml_id: n/a, model: ir.model.fields, parent_id: 36]
None" while parsing /home/mymodules/base_geoengine/geo_ir/ir_model_view.xml:4...

Please, can anyone help me with this?

**Comment by yvaucher** [comment]
@sarahosay What is the version of the module in __manifest__.py or __openerp__.py ?

Have you installed the following dependencies ?

http://oca.github.io/geospatial/prerequisite.html

**Comment by sarahosay** [comment]
The version in the manifest is '10.0.1.0.0'
Yes, i installed the ff.: geojson, shapely and postgis.

**Comment by otrikafo** [comment]
@sarahosay I have the same problem. have you find a solution?
I'm using odoo10 with python2.7.9

**Comment by Sixologue** [comment]
```
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-12.0/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-12.0/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo-12.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo-12.0/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-12.0/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-12.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-12.0/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-12.0/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-12.0/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-12.0/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-12.0/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-12.0/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "</home/mahenina/.local/lib/python3.6/site-packages/decorator.py:decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo/odoo-12.0/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo-12.0/odoo/addons/base/models/ir_module.py", line 444, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo-12.0/odoo/addons/base/models/ir_module.py", line 553, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo-12.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-12.0/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo-12.0/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo-12.0/odoo/modules/loading.py", line 186, in load_module_graph
    getattr(py_module, pre_init)(cr)
AttributeError: module 'odoo.addons.base_geoengine' has no attribute 'init_postgis'
```

**Comment by Sixologue** [comment]
help please

**Comment by wanteex** [comment]
Hi guys ! 
I have the same problem, Has anyone come up with a solution? :)

**Comment by yvaucher** [comment]
@wanteex a work around in 12.0 is to comment the line
https://github.com/OCA/geospatial/blob/12.0/base_geoengine/__manifest__.py#L35

See my message https://github.com/OCA/geospatial/issues/142#issuecomment-307362043

The init hook is just there to try to prepare the database.
It is weird that the CI doesn't catch this error.

**Comment by husain-erpharbor** [comment]
May be You are using the version 11 module of base_geoengine.clone version 10 module of base_geoengine from OCA community.
Here is the link.
https://github.com/OCA/geospatial.git

**Comment by yvaucher** [comment]
@husain-erpharbor your link might be obsolet soon as the main branch will be switched to 13.0

**Comment by fdoangulo** [comment]
I´m having the same error in odoo 12, with postgresql 12 and postgis 3.0.1

If I try the work around suggested by @yvaucher and comment line 35 in __manifest__.py and install extensions by hand, I get another error: "srid field does not exist".

Any suggestion?

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 186, in load_module_graph
    getattr(py_module, pre_init)(cr)
AttributeError: module 'odoo.addons.base_geoengine' has no attribute 'init_postgis'
```

**Comment by fdoangulo** [comment]
> I´m having the same error in odoo 12, with postgresql 12 and postgis 3.0.1
> 
> If I try the work around suggested by @yvaucher and comment line 35 in **manifest**.py and install extensions by hand, I get another error: "srid field does not exist".
> 
> Any suggestion?
> 
> ```
> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
>     result = self._call_function(**self.params)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
>     return self.method(*args, **kw)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
>     response = f(*args, **kw)
>   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
>     return _call_kw_multi(method, model, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "<decorator-gen-61>", line 2, in button_immediate_install
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
>     return self._button_immediate_function(type(self).button_install)
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
>     loaded_modules, update_module, models_to_check)
>   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
>     perform_checks=perform_checks, models_to_check=models_to_check
>   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 186, in load_module_graph
>     getattr(py_module, pre_init)(cr)
> AttributeError: module 'odoo.addons.base_geoengine' has no attribute 'init_postgis'
> ```

SOLVED: postgresql 12 has important changes from version 11. Instlling postgresql version 11 solves the problem.

**Comment by yvaucher** [comment]
@fdoangulo ok, thanks for the feed back.

Usually we want to support the psql version that Odoo officially supports.
In the context of OCA we run our tests only on postgres 9.6. It should work though on more recent versions.

To know against which version of postgres we are running our tests, you can check in the `.travis.yml`:

https://github.com/OCA/geospatial/blob/24e5832b6807f2757a9f12e26c3cff8c241b63bc/.travis.yml#L9

I'll rename this issue accordingly.
