### ISSUE TITLE
Install of base_geoengine

### ISSUE THREAD

**Issue by cedvict** [OCA/geospatial#145]
Hi,
I have this track when i try to install base_geoengine.
Someone can help me please?

Traceback (most recent call last):
  File "C:/environment/odoo.9\openerp\http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:/environment/odoo.9\openerp\http.py", line 636, in dispatch
    result = self._call_function(**self.params)
  File "C:/environment/odoo.9\openerp\http.py", line 315, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:/environment/odoo.9\openerp\service\model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:/environment/odoo.9\openerp\http.py", line 308, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:/environment/odoo.9\openerp\http.py", line 887, in __call__
    return self.method(*args, **kw)
  File "C:/environment/odoo.9\openerp\http.py", line 465, in response_wrap
    response = f(*args, **kw)
  File "c:\environment\odoo.9\openerp\addons\web\controllers\main.py", line 975, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\environment\odoo.9\openerp\addons\web\controllers\main.py", line 963, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "C:/environment/odoo.9\openerp\service\model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "c:\environment\odoo.9\openerp\addons\web\controllers\main.py", line 962, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "C:/environment/odoo.9\openerp\api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "c:\environment\odoo.9\openerp\addons\base\module\module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "C:/environment/odoo.9\openerp\api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "c:\environment\odoo.9\openerp\addons\base\module\module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "C:/environment/odoo.9\openerp\modules\registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:/environment/odoo.9\openerp\modules\loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "C:/environment/odoo.9\openerp\modules\loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "C:/environment/odoo.9\openerp\modules\loading.py", line 136, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "C:/environment/odoo.9\openerp\modules\registry.py", line 180, in setup_models
    model._setup_fields(cr, SUPERUSER_ID)
  File "C:/environment/odoo.9\openerp\api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:/environment/odoo.9\openerp\api.py", line 318, in old_api
    result = method(recs, *args, **kwargs)
TypeError: _setup_fields() takes exactly 2 arguments (1 given)

**Comment by yvaucher** [comment]
Hello @cedvict your odoo code base is not up to date as I see in your stacktrace:
```
File "C:/environment/odoo.9\openerp\modules\registry.py", line 180, in setup_models
model._setup_fields(cr, SUPERUSER_ID)
```
https://github.com/odoo/odoo/blob/9.0/openerp/modules/registry.py#L200

You need to have at least this commit:
https://github.com/odoo/odoo/commit/87d160a7423243ecd760fefe5ba22fb85c460cb6

**Comment by cedvict** [comment]
Thanks @yvaucher 
I was working on old version of odoo 9
It's working now

**Comment by cedvict** [comment]
Thanks @yvaucher 
I was working on old version of odoo 9
It's working now
