### ISSUE TITLE
Erro ao acessar contatos

### ISSUE THREAD

**Issue by falexandresilva** [OCA/geospatial#203]
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 939, in call
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo/odoo/models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo/l/geospatial/base_geoengine/geo_model.py", line 136, in fields_view_get
    submenu=submenu)
  File "/opt/odoo/odoo/models.py", line 1462, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 1096, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: O campo company_partner_id não existe

Contexto de erro:
Veja n/a
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

**Comment by pedrobaeza** [comment]
Can you try on runbot to see if you have the same error?

**Comment by falexandresilva** [comment]
I already solved, was an update error. Thanks.
