### ISSUE TITLE
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

### ISSUE THREAD

**Issue by WeeDom** [OCA/geospatial#204]
Setup
odoo 12 enterprise edition (retrieved 7th June 2019)
in a docker swarm with debian:stretch as the base
camptocamp/postgres:10.2 db

Steps to reproduce
* Start with non-existent database
* start odoo in container with `odoo --logfile=/var/log/odoo/odoo-server.log --dev=all` - db is specified as msuk12_e in odoo.conf but we're going to create it 
* go to gui. Enter db details and password from odoo.conf
* install Sale, Contacts, sale_management
* install base_geoengine from 12.0 branch here
* install custom module which extends sale.order to do geo things.
* click on Sale icon in gui

Expected behaviour

Sale module loads with customer data, and geo fields in "create sale order" view

Actual behavior

Error gets displayed.

`Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 262

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 980, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.actions.act_window(262,).search_view', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1262, in load
    action = request.env[action_type].browse([action_id]).read()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 210, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2787, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5098, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 984, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1095, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1051, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1042, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 170, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/home/miningsearchesuk/src/python/base_geoengine/geo_model.py", line 135, in fields_view_get
    return super().fields_view_get(
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1455, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1418, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 783, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 729, in apply_view_inheritance
    specs_tree = etree.fromstring(specs.encode('utf-8'))
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1`

This line in the stack is the significant one, I believe:

` File "/home/miningsearchesuk/src/python/base_geoengine/geo_model.py", line 135, in fields_view_get
    return super().fields_view_get(
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1455, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)`

I've set a breakpoint there and stepped through. I can't see why it's not finding a document.

I've also tried removing and re-installing base_geoengine. My sale.order modifications predictably complain. Also tried upgrading through the gui, and it throws another error:

`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'msuk12_e'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 240, in load
    model = cls._build_model(self, cr)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 439, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'sale.order' does not exist in registry.`

Any suggestions gratefully accepted.

**Comment by WeeDom** [comment]
stepping through with the pdb, I get to here and there's a document 

`> /usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py(767)read_combined()
-> view_arch = etree.fromstring(view_data['arch'].encode('utf-8'))
(Pdb) view_data
{'arch': '\n                <xpath expr="//filter[@name=\'my_sale_orders_filter\']" position="replace">\n                    <separator/>\n                    <filter string="My Quotations" name="my_quotation" domain="[(\'user_id\', \'=\', uid)]"/>\n                    <separator/>\n
              <filter string="Quotations" name="draft" domain="[(\'state\',\'in\',(\'draft\', \'sent\'))]"/>\n                    <filter string="Sales Orders" name="sales" domain="[(\'state\',\'in\',(\'sale\',\'done\'))]"/>\n                    <separator/>\n                    <filter string="Order Date" name="filter_order_date" date="date_order"/>\n                </xpath>\n            ', 'name': 'sale.order.search.inherit.quotation', 'id': 708, 'field_parent': False, 'type': 'search', 'model': 'sale.order'}
(Pdb)
`

**Comment by WeeDom** [comment]
when I loop round that function again (it recursively applies inheritance?) my odoo seems to stop. Re making the cache?

**Comment by WeeDom** [comment]
nothing to do with geospatial. Sorry - it's my custom code that's broken. 

Apologies
