### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tooltip' of undefined

### ISSUE THREAD

**Issue by fdoangulo** [OCA/geospatial#249]
Odoo 12-CE - Installations from scratch
Postgresql 11
Postgis 3.0.1

I have installed the modules without errors (base_geospatial & base_geospatial_demo). Both downloaded from the OCA apps store.

But when going to the GeoEngine Demo menu, and clicking on the map icon, the map doesn't loads.

I have a Docker installation with two containers: one for the web, and another for the db. The Shapely and the geojson are installed on the web container during the build process throught "apt-get install python3-shapely geojson".

I have no errors on the server log (Debug mode), and I don't know what else review.

I have updated npm, rtlcss and nodejs. Nothing works.

I have checked that it works ok on the OCA's runbot, so I discard browser's problems.

But when I enter into de GeoEngine Demo, and try to open any of the records, I get the following error:
```
Uncaught TypeError: Cannot read property 'tooltip' of undefined
http://192.168.1.5:8069/web/content/666-ebaefa3/web.assets_backend.js:1575
Rastreo de error:
TypeError: Cannot read property 'tooltip' of undefined
    at Class._addFieldTooltip (http://192.168.1.5:8069/web/content/666-ebaefa3/web.assets_backend.js:1575:735)
    at http://192.168.1.5:8069/web/content/666-ebaefa3/web.assets_backend.js:1663:343
    at Function._.each._.forEach (http://192.168.1.5:8069/web/content/654-1cebeb7/web.assets_common.js:12:558)
    at Class._updateView (http://192.168.1.5:8069/web/content/666-ebaefa3/web.assets_backend.js:1663:3)
    at http://192.168.1.5:8069/web/content/666-ebaefa3/web.assets_backend.js:1661:1373
    at http://192.168.1.5:8069/web/content/654-1cebeb7/web.assets_common.js:802:681
    at fire (http://192.168.1.5:8069/web/content/654-1cebeb7/web.assets_common.js:796:299)
    at Object.add [as done] (http://192.168.1.5:8069/web/content/654-1cebeb7/web.assets_common.js:797:467)
    at Array.<anonymous> (http://192.168.1.5:8069/web/content/654-1cebeb7/web.assets_common.js:802:649)
    at Function.each (http://192.168.1.5:8069/web/content/654-1cebeb7/web.assets_common.js:625:767)
```
Any suggestion?

**Comment by fdoangulo** [comment]
Seems the problem is that the OCA appstore module is outdated and gives problems with curren packages.
To solve the problem I just had to download the Github code and install the module.
