### ISSUE TITLE
Error in Map view after adding the API key in configuration

### ISSUE THREAD

**Issue by skh-sw** [OCA/geospatial#253]
After I add the API key in configurations, the following error is encountered when we switch to the map view of contacts.

Error:
Uncaught TypeError: Cannot read property 'equals' of undefined

http://localhost:1220/web/content/393-528d8f1/web.assets_backend.js:3415
Traceback:
TypeError: Cannot read property 'equals' of undefined
    at http://localhost:1220/web/content/393-528d8f1/web.assets_backend.js:3415:358
    at Array.forEach (<anonymous>)
    at Class._clusterAddMarker (http://localhost:1220/web/content/393-528d8f1/web.assets_backend.js:3415:275)
    at Class._createMarker (http://localhost:1220/web/content/393-528d8f1/web.assets_backend.js:3415:75)
    at http://localhost:1220/web/content/393-528d8f1/web.assets_backend.js:3417:1674
    at Function._.each._.forEach (http://localhost:1220/web/content/385-216c775/web.assets_common.js:12:558)
    at Class._renderUngrouped (http://localhost:1220/web/content/393-528d8f1/web.assets_backend.js:3417:1488)
    at Class._renderMarkers (http://localhost:1220/web/content/393-528d8f1/web.assets_backend.js:3417:941)
    at Class._renderView (http://localhost:1220/web/content/393-528d8f1/web.assets_backend.js:3422:556)
    at Class.prototype.<computed> [as _renderView] (http://localhost:1220/web/content/385-216c775/web.assets_common.js:3538:488)

Without the API key it loads the map widget without loading any kind of map data. Any help in addressing this issue will be greatly appreciated.

**Comment by TDu** [comment]
Hello @skh-sw , could you be more precise by giving the module name and version that is causing you some trouble.
Also it seems that the error happens in the javascript so enabling debug with assets could help with the stack trace.
Thank you

**Comment by yvaucher** [comment]
@skh-sw impossible to tell without more information, as @TDu said the debug mode is necessary to spot which line of javascript is the trouble maker.
