### ISSUE TITLE
Geo Spatial support demo failed to install

### ISSUE THREAD

**Issue by akram1** [OCA/geospatial#46]
I use Odoo 8 build July 2015 and latest geospatial. After installing all modules, I installed support demo module but failed and gave this error

Odoo Server Error

Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/media/akram/Data/projects/servers/Odoo/odoo8/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/addons/base/ir/ir_model.py", line 1077, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 4077, in create
    record = self.browse(self._create(old_vals))
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 4215, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ParseError: "Geometry SRID (0) does not match column SRID (900913)
" while parsing /media/akram/Data/projects/servers/Odoo/addons/odoo8/base_geoengine_demo/data/retail_machine_geom.xml:4, near
<record model="geoengine.demo.automatic.retailing.machine" id="machine_1">
         <field name="name">1</field>
         <field name="total_sales">1057</field>
         <field name="money_level">low</field>
         <field name="the_point">POINT(746676.106813609 5865349.7175855)</field>
         <field name="state">ok</field>
      </record>

System
configuration is
     Postgres SQL
         Version        9.4.1
         Location       runtime/bin/pgsql
         Port              65432
         Addons        geos-3.4.2
                             proj4-4.8.0
                             postgis-2.1.6
                             swig-3.0.4
     Python
         Version        2.7.8
         Location       runtime/bin/python
         Addons        aeroo-lib- 1.2.0
                         argparse-1.3.0
                         Babel-1.3
                         BeautifulSoup-3.2.1
                         beautifulsoup4-4.3.2
                         bz2file-0.98
                         crypto-1.3.4
                         decorator-3.4.0
                         daemonize-2.3.1
                           docutils-0.12
                         erppeek-1.6.1
                         fabric-1.10.1
                         feedparser-5.1.3
                         gdal-1.9.1
                         gdata-2.0.18
                         genshi-0.7
                         geoip2-2.1.0
                          geojson-3.6.5
                         geopy-0.95.1
                         gevent_psycopg2 -0.0.3
                         gevent-1.0.1
                         graphviz-0.4.3
                         greenlet-0.4.5
                         jcconv-0.2.3
                         ipdb-0.8
                         Jinja2-2.7.3
                         jsonrpc2-0.4.1
                          lxml-3.4.1
                         M2Crypto-0.22.3
                         Mako-1.0.1
                         markdown-2.6.2
                         MarkupSafe-0.23
                         mock-1.0.1
                         mygengo-1.3.3
                         openoffice-python-0.1.p
                          passlib-1.6.2
                         Pillow-2.8.1
                         pip-7.0.3
                         psutil-2.2.0
                         psycogreen-1.0
                         psycopg2-2.6
                         pudb-2015.2
                         py2cairo-1.10.0
                         py3o.template
                         PyChart-1.39
                         pycups-1.9.72
                         pydot-1.0.2
                         pygeoip-0.3.2
                         pygobject-3.16.0
                         pyinotify-0.9.6
                         pyparsing-2.0.3
                         pyPdf-1.13
                          pyPDF2-1.24
                         pyserial-2.7
                         pysqlite-2.6.3
                         python-dateutil-2.4.2
                         python-ldap-2.4.19
                         python-openid-2.2.5
                         pytz-2014.10
                         pyusb-1.0.0b2
                         PyWebDAV-0.9.8
                         PyYAML-3.11
                         qrcode-5.1
                         reportlab-3.1.44
                         requests-2.6.0
                         setuptools-15.0
                         shapely-1.5.7
                         simplejson-3.6.5
                         six-1.9.0
                         South-1.0.2
                         suds-0.4
                         ulif.openoffice
                         unittest2-0.8.0
                         uno-0.3.3
                         vatnumber-1.2
                          vobject-0.6.6
                         Werkzeug-0.10.4
                         wsgiref-0.1.2
                          xlwt-0.7.5
                          zkemapi-0.0.1
                         zsi-lxml-2.0-rc3

```
 Others         bzip2-1.0.6
                     cairo-1.14.2
                     curl-7.41.0
                     cyrus-sasl-2.1.23
                      db-5.3.21
                     fontconfig-2.11.0
                      freetype-2.5.5
                      gdbm-1.8.3
                     GeoIP
                     gettext-0.18.1.1
                     giflib-5.1.1
                     gdal-2.0.0
                     glib-2.44.0
                     gobject-introspection-1.44.0
                      graphviz-2.38.0
                      jpeg-9a
                     libedit-20150325-3.1
                      libev-4.19
                     libevent-2.0.17
                     libffi-3.2.1
                     libgcrypt-1.6.2
                     libgd-2.1.1
                     libgnutls-3.3.13
                     libgpg-error-1.17
                      libiconv-1.13.1
                     libpng-1.6.16
                      libxml2-2.9.2
                     libxslt-1.1.28
                     ncurses-5.9
                     openjpeg-1.5.1
                     openldap-2.4.40
                      openssh-5.8p1
                     openssl-1.0.2a
                     pcre-8.34
                     pixman-0.32.6
                      pkg-config-0.28
                     readline-6.2
                      sqlite3
                     tiff-4.0.3
                     wkhtmltopdf-0.12.2.1
                     zeromq-3.2.3
                     zlib-1.2.8
```

**Comment by lmignon** [comment]
@akram1 see #43 and the provided solution
