### ISSUE TITLE
base_geoengine fails to install

### ISSUE THREAD

**Issue by dreispt** [OCA/geospatial#47]
I'm testing the Geoengine project, but unfortunately am having trouble with the base module.
Yes, i read and followed the docs: installed postgis, pyhton dependencies, created a db to use, created the extensions on it, and cherry-picked odoo/#5620 (odoo/#5618 is already merged).

Nevertheless I still get this error when installing `base_geoengine` (with demo data):

```
2015-07-15 21:23:38,829 4730 INFO geospatial openerp.modules.loading: 16 modules loaded in 0.05s, 0 queries
2015-07-15 21:23:38,831 4730 INFO geospatial openerp.modules.loading: loading 17 modules...
2015-07-15 21:23:38,841 4730 CRITICAL geospatial openerp.modules.module: Couldn't load module base_geoengine
2015-07-15 21:23:38,841 4730 CRITICAL geospatial openerp.modules.module: invalid literal for int() with base 10: '2 r3921'
2015-07-15 21:23:38,841 4730 CRITICAL geospatial openerp.service.server: Failed to initialize database `geospatial`.
Traceback (most recent call last):
  File "/home/nitrous/odoo/openerp/service/server.py", line 929, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/nitrous/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/nitrous/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/nitrous/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/nitrous/odoo/openerp/modules/loading.py", line 143, in load_module_graph
    load_openerp_module(package.name)
  File "/home/nitrous/odoo/openerp/modules/module.py", line 315, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/home/nitrous/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/nitrous/geospatial/base_geoengine/__init__.py", line 22, in <module>
    from . import geo_model
  File "/home/nitrous/geospatial/base_geoengine/geo_model.py", line 27, in <module>
    from . import fields as geo_fields
  File "/home/nitrous/geospatial/base_geoengine/fields.py", line 21, in <module>
    from shapely.geometry import Point
  File "/usr/local/lib/python2.7/dist-packages/shapely/geometry/__init__.py", line 4, in <module>
    from geo import box, shape, asShape, mapping
  File "/usr/local/lib/python2.7/dist-packages/shapely/geometry/geo.py", line 5, in <module>
    from point import Point, asPoint
  File "/usr/local/lib/python2.7/dist-packages/shapely/geometry/point.py", line 7, in <module>
    from shapely.geos import lgeos, DimensionError
  File "/usr/local/lib/python2.7/dist-packages/shapely/geos.py", line 100, in <module>
    geos_capi_version = geos_c_version = _geos_c_version()
  File "/usr/local/lib/python2.7/dist-packages/shapely/geos.py", line 98, in _geos_c_version
    return tuple(int(n) for n in v.split('.'))
  File "/usr/local/lib/python2.7/dist-packages/shapely/geos.py", line 98, in <genexpr>
    return tuple(int(n) for n in v.split('.'))
ValueError: invalid literal for int() with base 10: '2 r3921'
```

Thanks in advance for your help.

**Comment by lmignon** [comment]
@dreispt by reading the stack trace it seems that your problem is related to the version used for shapely or a related lib. '2 r3921'

**Comment by dreispt** [comment]
Thanks. 
I followed the [install instructions](http://oca.github.io/geospatial/prerequisite.html#postgis-2-0):

```
pip install geojson
pip install Shapely==1.2.13
```

And I have:

```
➜  ~  pip show geojson
---
Name: geojson
Version: 1.2.2
Location: /usr/local/lib/python2.7/dist-packages
Requires: setuptools
➜  ~  pip show shapely
---
Name: Shapely
Version: 1.2.13
Location: /usr/local/lib/python2.7/dist-packages
Requires:
```

Any clue on where should I look next?

**Comment by lmignon** [comment]
@dreispt Can you try with the latest version of shapely? (1.5.9) The one referenced in the documentation is old and I personally use the latest version of shapely

**Comment by dreispt** [comment]
Yes, that solved, thanks for your help.
Doing a PR to fix the docs.

**Comment by treviser** [comment]
Could you please update the documentation, as it still mentions shapely 1.2.13?
http://oca.github.io/geospatial/prerequisite.html#postgis-2-0
