### ISSUE TITLE
error install geo demo data in odoo 8 

### ISSUE THREAD

**Issue by fadeldamen** [OCA/geospatial#50]
raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: base_geoengine_demo.field_dummy_zip_total_sales" while parsing /home/fadel/desarrollo/geospatial/base_geoengine_demo/zip_view.xml:71, near
<record id="geoengine_vector_layer_coloredrangetest0" model="geoengine.vector.layer">
            <field name="geo_field_id" ref="base_geoengine_demo.field_dummy_zip_the_geom"/>
            <field name="name">Colored range ZIP</field>
            <field name="classification">unique</field>
            <field eval="6" name="sequence"/>
            <field name="view_id" ref="ir_ui_view_resbetterzipgeoview0"/>
            <field name="geo_repr">colored</field>
            <field eval="1" name="nb_class"/>
            <field name="attribute_field_id" ref="base_geoengine_demo.field_dummy_zip_total_sales"/>
            <field name="begin_color">#FF680A</field>
        </record>

**Comment by lmignon** [comment]
@fadeldamen it seems you use an old version of odoo previous to the merge of https://github.com/odoo/odoo/pull/5618

**Comment by jacksolutions** [comment]
i have odoo8 and on fresh install of new DB i am getting below error when updating modules list

2015-08-14 11:12:18,176 10580 ERROR postgis openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 393, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 397, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/odoo-server/openerp/addons/base/module/wizard/base_module_update.py", line 15, in update_module
    self.updated, self.added = self.env['ir.module.module'].update_list()
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 654, in update_list
    handler.load_addons()
  File "/opt/odoo/odoo-server/openerp/http.py", line 1298, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/odoo/odoo-server/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/custom/addons/base_geoengine/**init**.py", line 22, in <module>
    from . import geo_model
  File "/opt/odoo/custom/addons/base_geoengine/geo_model.py", line 26, in <module>
    from . import geo_operators
ImportError: cannot import name geo_operators

**Comment by jacksolutions** [comment]
just to confirm, i have installed postgis, shapely and geojson too.

**Comment by lmignon** [comment]
@jacksolutions Do you have a fresh install of Odoo 8.0 (not only a new DB but do you have the sources of Odoo up to date)?

**Comment by jacksolutions** [comment]
yes i have odoo 8.0 latest sources and odoo is up to date.

On Fri, Aug 14, 2015 at 4:59 PM, Laurent Mignon (ACSONE) <
notifications@github.com> wrote:

> @jacksolutions https://github.com/jacksolutions Do you have a fresh
> install of Odoo 8.0 (not only a new DB but do you have the sources of Odoo
> up to date)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/geospatial/issues/50#issuecomment-131082748.

## 

Cheers,

Jaykishan Vansadawala
(Jack Solutions)
Mob:- +91-9879455635

**Comment by lmignon** [comment]
@fadeldamen Is your problem solved?

**Comment by fadeldamen** [comment]
sorry yes I update odoo server and solved problem

2015-09-17 7:58 GMT-04:00 Laurent Mignon (ACSONE) notifications@github.com
:

**Comment by lmignon** [comment]
@fadeldamen Thank you for the feedback.

**Comment by msdgithub** [comment]
I do have the same issue as reported by jacksolutions. I have the latest version of odoo 8 running. however, i can not make it work. Any ideas how to fix the problem?
I am not sure if this part mentioned in the installation guide has to do with it:
http://oca.github.io/geospatial/installation.html
Thanks for all your help!

**Comment by lmignon** [comment]
@msdgithub The part mentioned in the installation (merging PR https://github.com/odoo/odoo/pull/5620)  is a prerequisite to have the module working. Do you have applied these changes  into your Odoo 8?
