### ISSUE TITLE
NameError: global name 'wkt' is not defined

### ISSUE THREAD

**Issue by pooyakntu** [OCA/geospatial#57]
module: base_geoengine
version: 8.0

**Steps to reproduce**

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\http.py", line 537, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\http.py", line 574, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\http.py", line 310, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\http.py", line 307, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\http.py", line 803, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\http.py", line 403, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server\openerp\addons\web\controllers\main.py", line 944, in call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\api.py", line 250, in wrapper
  File "C:\Users\Pooya\AppData\Local\OpenERP S.A.\Odoo\addons\8.0\base_geoengine\geo_model.py", line 152, in fields_view_get
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server\openerp\addons\base\res\res_partner.py", line 332, in fields_view_get
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\api.py", line 345, in old_api
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server\openerp\addons\base\res\res_partner.py", line 64, in fields_view_get_address
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\fields.py", line 819, in __get__
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\fields.py", line 912, in determine_value
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\api.py", line 248, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\models.py", line 3241, in _prefetch_field
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\api.py", line 248, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\models.py", line 3178, in read
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\api.py", line 248, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\models.py", line 3352, in _read_from_database
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\osv\fields.py", line 1454, in get
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server\openerp\addons\base\res\res_company.py", line 85, in _get_address_data
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server\openerp\addons\base\res\res_partner.py", line 756, in address_get
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\fields.py", line 819, in __get__
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\fields.py", line 912, in determine_value
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\api.py", line 248, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\models.py", line 3241, in _prefetch_field
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\api.py", line 248, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20151023\server.\openerp\models.py", line 3189, in read
  File "C:\Users\Pooya\AppData\Local\OpenERP S.A.\Odoo\addons\8.0\base_geoengine\fields.py", line 47, in convert_to_read
  File "C:\Users\Pooya\AppData\Local\OpenERP S.A.\Odoo\addons\8.0\base_geoengine\geo_helper\geo_convertion_helper.py", line 36, in value_to_shape
NameError: global name 'wkt' is not defined

**Comment by lmignon** [comment]
@pooyakntu It seems that you didn't have installed the required dependencies.(see https://github.com/OCA/geospatial#requirements). wkt is provided by shapely.

**Comment by lmignon** [comment]
@pooyakntu Feel free to reopen the issue if the provided answer doesn't solve your problem.
