### ISSUE TITLE
Error Install module demo

### ISSUE THREAD

**Issue by lammh** [OCA/geospatial#76]
![image](https://cloud.githubusercontent.com/assets/7395544/13028322/f089054c-d26b-11e5-97eb-451519963855.png)

**Comment by yvaucher** [comment]
@lammh With which version of the module ?

**Comment by lammh** [comment]
@yvaucher  module 8.0.0.1.0

**Comment by yvaucher** [comment]
@lammh `total_sales` field of model `dummy.zip` is defined here
https://github.com/OCA/geospatial/blob/8.0/base_geoengine_demo/geo_npa.py#L37-L40

Have you removed anything ? It was working properly on runbot.

**Comment by lammh** [comment]
@yvaucher ,no a don't remove anything!
i have reinstall a model but a have a error!

**Comment by ayepezv** [comment]
Saludos tengo el error al instalar el geospatial_demo me sale el siguiente codigo, y para desinstalar me indica cancelar instalacion, si me podrian ayudar, gracias de antemano. Uso Odoo 9 y geospatial del 9 mismo.

Odoo Server Error
Traceback (most recent call last):
  File "/home/andres/git/odoo9/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/andres/git/odoo9/openerp/http.py", line 680, in dispatch
    result = self._call_function(*_self.params)
  File "/home/andres/git/odoo9/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/andres/git/odoo9/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/andres/git/odoo9/openerp/http.py", line 309, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/home/andres/git/odoo9/openerp/http.py", line 959, in __call__
    return self.method(_args, *_kw)
  File "/home/andres/git/odoo9/openerp/http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "/home/andres/git/odoo9/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/andres/git/odoo9/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/andres/git/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/andres/git/odoo9/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/andres/git/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/andres/git/odoo9/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/andres/git/odoo9/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/andres/git/odoo9/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/home/andres/git/odoo9/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/andres/git/odoo9/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/andres/git/odoo9/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/andres/git/odoo9/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/andres/git/odoo9/openerp/tools/convert.py", line 921, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "lxml.etree.pyx", line 3239, in lxml.etree.parse (src/lxml/lxml.etree.c:69955)
  File "parser.pxi", line 1769, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:102257)
  File "parser.pxi", line 1789, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:102516)
  File "parser.pxi", line 1684, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:101442)
  File "parser.pxi", line 1134, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:97069)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91757)
XMLSyntaxError: Document is empty, line 1, column 1

**Comment by yvaucher** [comment]
@lammh I'm closing this issue as base_geoengine_demo module installs correctly on 
https://travis-ci.org/OCA/geospatial/jobs/200560127
(error is due to module geoengine_project)

@ayepezv Please use english and create your own issue, your error doesn't seems related
