### ISSUE TITLE
'bool' object is not iterable

### ISSUE THREAD

**Issue by sciallo** [OCA/geospatial#86]
module: base_geoengine
version: 8.0 (9.0.1.1.0 in **openerp**.py I guess the link in README.rst could use an update)

**Steps to reproduce**
- attempt to install base_geoengine on latest OCB odoo
  This started happening after 'git pull'ed last version of OCB it was working before. I tried starting with blank database, still no Joy. (new database manually postgisified)

**Current behavior**
Traceback (most recent call last):
  File "/home/jennon/odoo/odoo9c/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/jennon/odoo/odoo9c/openerp/http.py", line 680, in dispatch
    result = self._call_function(*_self.params)
  File "/home/jennon/odoo/odoo9c/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/jennon/odoo/odoo9c/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/jennon/odoo/odoo9c/openerp/http.py", line 309, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/home/jennon/odoo/odoo9c/openerp/http.py", line 959, in __call__
    return self.method(_args, *_kw)
  File "/home/jennon/odoo/odoo9c/openerp/http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "/home/jennon/odoo/odoo9c/addons/web/controllers/main.py", line 897, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/jennon/odoo/odoo9c/addons/web/controllers/main.py", line 885, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/jennon/odoo/odoo9c/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/jennon/odoo/odoo9c/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/jennon/odoo/odoo9c/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/jennon/odoo/odoo9c/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/jennon/odoo/odoo9c/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/jennon/odoo/odoo9c/openerp/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/home/jennon/odoo/odoo9c/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/jennon/odoo/odoo9c/openerp/modules/loading.py", line 136, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "/home/jennon/odoo/odoo9c/openerp/modules/registry.py", line 200, in setup_models
    model._setup_fields(cr, SUPERUSER_ID, partial)
  File "/home/jennon/odoo/odoo9c/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/jennon/odoo/odoo9c/openerp/api.py", line 353, in old_api
    recs = self.browse(cr, uid, [], context)
  File "/home/jennon/odoo/odoo9c/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/jennon/odoo/odoo9c/openerp/models.py", line 5361, in browse
    return self._browse(Environment(cr, uid, context or {}), ids)
  File "/home/jennon/odoo/odoo9c/openerp/api.py", line 752, in __new__
    self.cr, self.uid, self.context = self.args = (cr, uid, frozendict(context))
TypeError: 'bool' object is not iterable

**Comment by jmabe** [comment]
Same error for me

Here is the odoo commit that is causing the problem:
87d160a7423243ecd760fefe5ba22fb85c460cb6 [FIX] models: partial loading of manual fields 

I'm not able to correct the problem so I did:
 git reset --hard a445fc996b1884345324714d2fe9513b102db00c

To make the module installable again.
May be it could help someone.

**Comment by yvaucher** [comment]
This should fix it: https://github.com/OCA/geospatial/pull/87
